general {
    no_fade_in = true
    no_fade_out = true
    hide_cursor = false
    grace = 0
    disable_loading_bar = true
}

background {
    path = $HOME/.config/wallpapers/wallpaper.jpg
    blur_passes = 1
    contrast = 1
    brightness = 0.5
    vibrancy = 0
}

input-field {
    size = 500, 80
    rounding = 0
    dots_size = 0.15
    dots_spacing = 0.5
    radius = 0
    outline_thickness = 1
    outer_color = rgba(40404000)
    inner_color = rgba(20202000)
    font_color = rgb(ffffff)
    check-text =
    placeholder_text = <i><span foreground="##cdd6f4">...</span></i>
}

